//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public Nullable<long> Phone_Number { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public string Type { get; set; }
        public string Vendor_Company_Code { get; set; }
    
        public virtual VendorCompany VendorCompany { get; set; }
    }
}
